### ISSUE TITLE
Minify error

### ISSUE THREAD

**Issue by clarghi** [trullock/NUglify#208] opened 2020-12-01 19:41 UTC
Hi,
Seems that fails to create the minified file when use parameter with default values in some circumstances.

Try this:

`var test={};
test.subNameSpace={
    failureTesting:() => {
        var sub=(info=false) => { console.log("ok "+info) };
        sub(true);
    }
}
window.onload=function() {
    test.subNameSpace.failureTesting();
}`

This simple code create a wrong javascript; the compressed file begin with:

`var test={};test.subNameSpace={failureTesting:()=>{var n=n=false=>{console.log`

var n=n=false is an error (missing brackets).

B.r.
Cristiano Larghi

**Comment by trullock** [comment] 2020-12-02 07:30
What version of NUglify are you using?

And what parameters are you passing to NUglify to encounter this issue?

I can't reproduce it with your example

**Comment by trullock** [comment] 2020-12-02 07:32
See: https://github.com/trullock/NUglify/blob/bug_208/src/NUglify.Tests/TestData/JS/Input/Bugs/Bug208.js and https://github.com/trullock/NUglify/blob/bug_208/src/NUglify.Tests/TestData/JS/Expected/Bugs/Bug208.js

**Comment by trullock** [comment] 2020-12-02 07:34
RE https://github.com/madskristensen/BundlerMinifier/issues/524
Closing as BundlerMinifier uses an ancient NUglify version.

Reopen this if I'm wrong and it still occurs on latest NUglify

**Comment by clarghi** [comment] 2020-12-02 07:34
Hi,
I use BundleMinifier (https://github.com/madskristensen/BundlerMinifier), which use NUglify 1.9.1.

**Closed by trullock** 2020-12-02 07:34 UTC

**Comment by trullock** [comment] 2020-12-02 07:52
Yep, ancient. Bundlerminifier needs updating
