### ISSUE TITLE
PreserveFunctionNames Js Settings

### ISSUE THREAD

**Issue by vicmr89** [trullock/NUglify#87] opened 2020-03-09 12:44 UTC
When I set PreserveFunctionNames = true, Nuglify changes some functions names:

Example:

	CodeSettings settings = new CodeSettings();
	settings.ReorderScopeDeclarations = false;
	settings.RemoveFunctionExpressionNames = false;
	settings.RemoveUnneededCode = false;
	settings.TermSemicolons = true;
	settings.PreserveFunctionNames = true;
	var result = Uglify.Js("function a(){this.prueba=prueba2; function prueba2(){alert(hola);}", settings);

Prueba2 function changes his name.

**Comment by trullock** [comment] 2020-06-09 15:31
I can't repro see, see the PR.

@vicmr89 can you edit the PR to reproduce your issue?

Note that master has some bugfixes which are not published to nuget yet, so work against that

**Comment by life777** [comment] 2020-06-12 20:58
@trullock 
I can reproduce it. I use latest master code in my small example (I just copied code from first comment)
![Screenshot from 2020-06-12 16-53-52](https://user-images.githubusercontent.com/891497/84545554-76d27a80-accd-11ea-893e-783a9bdcf471.png)

Original:
```js
function a(){this.prueba=prueba2; function prueba2(){alert(hola);}
```

Result:
```js
function a(){this.prueba=n;function n(){alert(hola)}}
```

Looks like name of the function `prueba2` is replaced with `n`

**Comment by life777** [comment] 2020-06-12 21:53
@trullock 
Fix in this case is simple. When code is iterating the lexical declared names we pass to the `DefineField` function a lexical declaration of the function:
![screenshot_4](https://user-images.githubusercontent.com/891497/84548882-b05ab400-acd4-11ea-9c55-24f579ad7d73.png)

but inside the function we check whether this lexical declaration is a FunctionObject, but we should check its parent:
![screenshot_3](https://user-images.githubusercontent.com/891497/84549022-fb74c700-acd4-11ea-98d9-528743fde0e0.png)

It fixes this problem, but it fixes only `Function Declaration` names, but not `Function Expression`:
Input:
```js
() => { let hello=()=>{}; function world(){}}
```
Result:
```js
()=>{let n=()=>{};function world(){}}
```

Should `Function Expression` also be fixed in this case?

**Comment by trullock** [comment] 2020-06-13 09:40
> Should `Function Expression` also be fixed in this case?

Probably, lets make a separate issue and test

**Closed** 2020-10-14 14:06 UTC
Labels: bug
