### ISSUE TITLE
Tag removed when uglifying html

### ISSUE THREAD

**Issue by henrikstengaard** [trullock/NUglify#333] opened 2022-08-07 08:23 UTC
**Describe the bug**
I'm using latest version of NUglify v1.20.2 and tried to uglify some simple html with div and p tags resulting end p tag is removed.

**To Reproduce**
Following code can reproduce the issue:
```
var html = @"<div>
     <p>
A paragraph with some text    
</p>

</div>";

var result = NUglify.Uglify.Html(html);

Console.WriteLine(result.Code);
```

**Minified output or stack trace**
```
<div><p>A paragraph with some text</div>
```

**Excepted output code**
```
<div><p>A paragraph with some text</p></div>
```

**Comment by trullock** [comment] 2022-08-07 08:33
This is by design. Modern browsers don't need the closing p, hence a useful minification

**Closed by trullock** 2022-08-07 08:33 UTC
