### ISSUE TITLE
Const variables being re-declared

### ISSUE THREAD

**Issue by Jman012** [trullock/NUglify#117] opened 2020-06-24 19:20 UTC
I've come across a funny issue. A const variable is being given the same minified variable name as another item in scope. At runtime, this leads to the const having the variable of the previous item.

Source code:
```js
DateInput.prototype.ValidateDate = function (options) {
	options = {
		isRequired: options.isRequired || false,
		upperBoundYears: options.upperBoundYears || 100,
		lowerBoundYears: options.lowerBoundYears || 100,
		comparedToToday: options.comparedToToday || "any",
		afterDate: options.afterDate || "",
		afterDateDescription: options.afterDateDescription || "",
		beforeDate: options.beforeDate || "",
		beforeDateDescription: options.beforeDateDescription || "",
	};

	const sDate = this.GetDateString();

	const hasValue = Common.ValidateText(sDate);
	if (options.isRequired && !hasValue) {
		return "This date is required";
	}

	if (hasValue) {
		if (!Common.IsValidDate(sDate)) {
			return "This date is invalid";
		}

		const momentDate = this.GetDateMoment();
		var now = moment();

		if (options.lowerBoundYears > 0 && momentDate.year() < (now.year() - options.lowerBoundYears)) {
			return "This date is too old";
		}
		if (options.upperBoundYears > 0 && momentDate.year() > (now.year() + options.upperBoundYears)) {
			return "This date is too far in the future";
		}
		if (options.comparedToToday == "after" && momentDate.isBefore(now)) {
			return "This date must be equal to or greater than current date";
		}
		if (options.comparedToToday == "before" && momentDate.isAfter(now)) {
			return "This date must be equal to or less than current date";
		}
		if (Common.ValidateText(options.afterDate) && Common.IsValidDate(options.afterDate) && momentDate.isBefore(moment(options.afterDate, "MM-DD-YYYY"))) {
			return "This date must come after " + options.afterDateDescription;
		}
		if (Common.ValidateText(options.beforeDate) && Common.IsValidDate(options.beforeDate) && !momentDate.isBefore(moment(options.beforeDate, "MM-DD-YYYY"))) {
			return "This date must come before " + options.beforeDateDescription;
		}
	}
};
```

Pretty-printed (Chrome), minified code:
```js
DateInput.prototype.ValidateDate = function(n) {
    n = {
        isRequired: n.isRequired || !1,
        upperBoundYears: n.upperBoundYears || 100,
        lowerBoundYears: n.lowerBoundYears || 100,
        comparedToToday: n.comparedToToday || "any",
        afterDate: n.afterDate || "",
        afterDateDescription: n.afterDateDescription || "",
        beforeDate: n.beforeDate || "",
        beforeDateDescription: n.beforeDateDescription || ""
    };
    const i = this.GetDateString()
      , r = Common.ValidateText(i);
    if (n.isRequired && !r)
        return "This date is required";
    if (r) {
        if (!Common.IsValidDate(i))
            return "This date is invalid";
        const r = this.GetDateMoment();
        var t = moment();
        if (n.lowerBoundYears > 0 && r.year() < t.year() - n.lowerBoundYears)
            return "This date is too old";
        if (n.upperBoundYears > 0 && r.year() > t.year() + n.upperBoundYears)
            return "This date is too far in the future";
        if (n.comparedToToday == "after" && r.isBefore(t))
            return "This date must be equal to or greater than current date";
        if (n.comparedToToday == "before" && r.isAfter(t))
            return "This date must be equal to or less than current date";
        if (Common.ValidateText(n.afterDate) && Common.IsValidDate(n.afterDate) && r.isBefore(moment(n.afterDate, "MM-DD-YYYY")))
            return "This date must come after " + n.afterDateDescription;
        if (Common.ValidateText(n.beforeDate) && Common.IsValidDate(n.beforeDate) && !r.isBefore(moment(n.beforeDate, "MM-DD-YYYY")))
            return "This date must come before " + n.beforeDateDescription
    }
}
;
```

The variables in question are `const hasValue` and `const momentDate`. They both are given the term `r` in the minified code. Thus, after the line `const r = this.GetDateMoment();`, the value of `r` is still `true` from the line `const r = Common.ValidateText(i);`.

This is being used via BuildBundlerMinifier, with the following configuration:
```json
	{
		"outputFileName": "js/Bundled/controls.js",
		"inputFiles": [
			"js/ApplicantID.logic.js",
			"js/DateInput.logic.js"
		],
		"minify": {
			"enabled": true
		},
		"sourceMap": false
	}
```

Where the ApplicantID.logic.js file is similar to the code snippet above: a top-level function and some prototype settings. Both files use const and var, no let, no module/exports. I say this because I know NUglify attempts to determine the ES version of the file. So, this is fairly narrowed-down in scope.

**Comment by trullock** [comment] 2020-07-06 07:54
OK, just fixed a similar issue to this you must have found another case.

Can you make  PR with a failing test? See `Bugs.cs` under the JS folder, make an input and expected `js` file that repros this and I'll take a look

**Comment by trullock** [comment] 2020-07-06 07:56
Ughh we havent merged that fix yet. This is probably solved by #76. I'll get that merged and you can retest

**Comment by trullock** [comment] 2020-07-06 08:17
v1.6.4 should be published shortly containing this fix, please report back 👍

**Comment by trullock** [comment] 2020-08-21 08:21
@Jman012 👋

**Comment by trullock** [comment] 2020-08-24 21:17
This isn't fixed, I shall investigate

**Comment by trullock** [comment] 2020-08-25 09:01
@Jman012 what runtime engine gives you errors?

Is the below reduction an accurate reproduction of your case?

```
const x = 1;

if(x){
  const x = 2;
  console.log(x);
}
```

because this is valid JS, isnt it?

You can redefine names with `const` and `let` in an inner block scope, which is what you're doing?

**Comment by trullock** [comment] 2020-08-25 10:19
Closing this as I'm pretty sure this is valid and your code isn't buggy.

Provide a repro if you disagree

thanks

**Closed by trullock** 2020-08-25 10:19 UTC
Labels: question
