### ISSUE TITLE
Duplicate property name

### ISSUE THREAD

**Issue by mmiller678** [trullock/NUglify#279] opened 2021-10-27 15:43 UTC
My issue seems similar to #264 

I am minimizing bootstrap.js (version 5.1.3) and getting the error message:
Strict-mode does not allow duplicate property names: ...Manipulator.getDataAttributes(this)

I am using NUglify version 1.16.1.  It seems this issue should be fixed but I am still seeing a similar issue.

JavaScript file to minimize:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.js

Exception:
```[NUglifyParsingException: Message: Strict-mode does not allow duplicate property names: ...Manipulator.getDataAttributes(this)
Error code: JS1292
Severity: 0
Subcategory: run-time
File: /lib/bootstrap/js/bootstrap.js
Start line: 1588
Start column: 9
End line: 1588
End column: 47]
   BundleTransformer.NUglify.Minifiers.NUglifyJsMinifier.ParserErrorHandler(Object source, ContextErrorEventArgs args) +70
   NUglify.JavaScript.JSParser.OnCompilerError(UglifyError se) +114
   NUglify.JavaScript.SourceContext.HandleError(JSError errorId, Boolean forceToError) +384
   NUglify.JavaScript.Visitors.<>c__DisplayClass54_0.<Visit>b__1(ObjectLiteralProperty property) +426
   NUglify.JavaScript.Syntax.AstNodeList.ForEach(Action`1 action) +177
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(ObjectLiteral node) +320
   NUglify.JavaScript.Syntax.ObjectLiteral.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(VariableDeclaration node) +61
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(VariableDeclaration node) +34
   NUglify.JavaScript.Syntax.VariableDeclaration.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(LexicalDeclaration node) +133
   NUglify.JavaScript.Syntax.LexicalDeclaration.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node) +912
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(FunctionObject node) +1522
   NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(AstNodeList node) +94
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(ClassNode node) +101
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(ClassNode node) +45
   NUglify.JavaScript.Syntax.ClassNode.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node) +912
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(FunctionObject node) +1522
   NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(AstNodeList node) +94
   NUglify.JavaScript.Visitors.TreeVisitor.Visit(CallExpression node) +57
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(CallExpression node) +2805
   NUglify.JavaScript.Syntax.CallExpression.Accept(IVisitor visitor) +36
   NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node) +912
   NUglify.JavaScript.JSParser.InternalParse() +2665
   BundleTransformer.NUglify.Minifiers.NUglifyJsMinifier.InnerMinify(IAsset asset, JSParser jsParser) +315

[AssetMinificationException: During minification of JS code, readed from the file '/lib/bootstrap/js/bootstrap.js', by NUglify JS minifier syntax error has occurred. 
See more details:

Message: Strict-mode does not allow duplicate property names: ...Manipulator.getDataAttributes(this)
Error code: JS1292
Severity: 0
Subcategory: run-time
File: /lib/bootstrap/js/bootstrap.js
Start line: 1588
Start column: 9
End line: 1588
End column: 47```

**Comment by trullock** [comment] 2021-11-21 21:22
Can you isolate the JS that causes this, as opposed to the whole of bootstrap?

**Comment by failwyn** [comment] 2022-01-06 00:41
This is caused by the following syntax in the Carousel class of bootstrap in the dataApiClickHandler function.

```
const config = { ...Manipulator.getDataAttributes(target),
    ...Manipulator.getDataAttributes(this)
}; 
```

// Bundler & Minifier is using NUglify and this is from a bug reported by one of the users
// https://github.com/failwyn/BundlerMinifier/issues/2

**Comment by shelland** [comment] 2022-01-12 12:11
Any update on this issue?

**Comment by jzabroski** [comment] 2022-01-12 21:18
Seems to have been broken for a long time https://github.com/madskristensen/BundlerMinifier/issues/414

**Comment by trullock** [comment] 2022-01-12 21:22
Pull requests welcome

**Comment by jzabroski** [comment] 2022-01-12 21:33
I don't know where to start.

**Comment by failwyn** [comment] 2022-01-12 22:53
I don’t have time to start from scratch, but if you can give me some hints of where the responsible code is, I’d be happy to take a look at it.

**Comment by trullock** [comment] 2022-01-13 13:03
ive pushed a branch `bug_279` with a test for this, which passes, the repro above doesn't repro any issue. 

Your first step is to make a failing test

**Comment by shelland** [comment] 2022-01-13 14:04
To make a failing test you just need to add `"use strict";` to the beginning of the JS file. I'm not a JS expert, but is this error caused by violating of some JS/ES guidelines? Maybe we need to report this issue directly to the Bootstrap project?

**Comment by trullock** [comment] 2022-01-13 14:50
im not sure if their syntax works as expected, but its not a syntax error.

The error is here https://github.com/trullock/NUglify/blob/9e2ee25d2d39aad97e0d0b6f387f1170b625b065/src/NUglify/JavaScript/Visitors/AnalyzeNodeVisitor.cs#L3372

Becuase the PropertyValue is a `CallExpression`, it ends up getting `ToString`ed and then becomes equal to any other call expression. This needs wisening to handle such situations properly

**Comment by trullock** [comment] 2022-01-14 20:15
Fixed in 1.17.8 - crudely :/

**Comment by leppie** [comment] 2022-09-15 10:22
Fails on Bootstrap 5.2 again

Culprit code:

```
    _mergeConfigObj(config, element) {
      const jsonConfig = isElement(element) ? Manipulator.getDataAttribute(element, 'config') : {}; // try to parse

      return { ...this.constructor.Default,
        ...(typeof jsonConfig === 'object' ? jsonConfig : {}),
        ...(isElement(element) ? Manipulator.getDataAttributes(element) : {}),
        ...(typeof config === 'object' ? config : {})
      };
    }
```

```
Strict-mode does not allow duplicate property names: ...(isElement(element) ? Manipulator.getDataAttributes(element) : {})
Strict-mode does not allow duplicate property names: ...(typeof config === 'object' ? config : {})
```

**Comment by nickl-** [comment] 2022-11-24 01:08
The new [Release v1.20.3](https://github.com/trullock/NUglify/releases/tag/v1.20.3) resolves this issue.

The above "Culprit code" reported by @leppie can now successfully be minified as:

```
_mergeConfigObj(n,t){const i=w(t)?k.getDataAttribute(t,"config"):{};return{...this.constructor.Default,...(typeof i=="object"?i:{}),...(w(t)?k.getDataAttributes(t):{}),...(typeof n=="object"?n:{})}}
```

Tested with bootstrap 5.2.2 bundle.js

**Comment by trullock** [comment] 2022-11-24 20:05
@leppie can you confirm this is fixed and close if so? Thanks

**Comment by trullock** [comment] 2022-12-07 12:01
@zhangyiatmicrosoft can you open a new issue with full repro, output and expected results please

**Comment by zhangyiatmicrosoft** [comment] 2022-12-07 22:09
> The above is the simplified version and the original full class is at https://github.com/mapbox/tiny-sdf/blob/main/index.js

Thank you. Done. #345

**Comment by jzabroski** [comment] 2023-02-15 15:53
@trullock @zhangyiatmicrosoft  Is this issue resolved now?  I realize we have had several re-openings of this general issue over the years.  But are there any known defects?  https://github.com/trullock/NUglify/issues/345#issuecomment-1404777412

Note, many of us are consuming NUglify through BundleTransformer.NUglify package, and consumers need at least [1.13.2](https://www.nuget.org/packages/BundleTransformer.NUglify/1.13.2) of that package for this to work end-to-end.

**Comment by trullock** [comment] 2023-02-15 20:12
Bundlerminifier really needs to update their repo to just depend on 1.x of Nuglify.

@leppie needs to confirm if this is fixed. I'm gonna close this as I guess so.

**Closed by trullock** 2023-02-15 20:12 UTC
Labels: bug, PR Welcome!

**Comment by zhangyiatmicrosoft** [comment] 2023-02-17 00:54
@jzabroski I am not sure about your issue. The specific case reported in #345 is fixed and I also added test case for it.
